"""
Django settings for autonew project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os 



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&!fr6jltkve_c*kad+))rbb#j++d@_jp-_8-+fsnos+!_!0_m7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'lavado_auto',
    'tailwind',
    'theme',
    'django_browser_reload',
    'django.contrib.humanize',
]

TAILWIND_APP_NAME = 'theme'

INTERNAL_IPS = ['127.0.0.1']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'lavado_auto.middleware_active_user.ActiveUserMiddleware',  # Verificar usuarios activos
    'django.contrib.messages.middleware.MessageMiddleware',
    'lavado_auto.middleware.AdminCRUDMiddleware',  # Middleware reactivado
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_browser_reload.middleware.BrowserReloadMiddleware',
]

ROOT_URLCONF = 'autonew.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'autonew.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


#load_dotenv()

#DATABASES = {
   # 'default': {
       # 'ENGINE': 'django.db.backends.postgresql',
        #'NAME': 'postgres',
        #'USER': os.getenv('DB_USER', 'postgres'),
        #'PASSWORD': os.getenv('DB_PASSWORD', ''),
        #'HOST': os.getenv('DB_HOST', ''),
        #'PORT': os.getenv('DB_PORT', '5432'),
        #'OPTIONS': {
         #   'sslmode': 'require',  # Supabase requiere SSL
        #},
    #}
#}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
AUTH_USER_MODEL = 'lavado_auto.Usuario'

USERNAME_FIELD = 'nombre_usuario'
EMAIL_FIELD = 'correo'

# Configuración para redirecciones de login
LOGIN_URL = 'login'  # URL a la que se redirige cuando se requiere login
LOGIN_REDIRECT_URL = 'homecrud'  # URL a la que se redirige después de login exitoso
LOGOUT_REDIRECT_URL = 'home'  # URL a la que se redirige después de logout

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "theme" / "static",
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de correo electrónico
# Para desarrollo, usaremos la consola (los correos se mostrarán en la terminal)
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Para producción, descomenta y configura lo siguiente:
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'du28fo@gmail.com'  # Cambia por tu correo
EMAIL_HOST_PASSWORD = 'ejxb aayi vydq omge'  # Usa contraseña de aplicación

DEFAULT_FROM_EMAIL = 'AutoNew <noreply@autonew.com>'
EMAIL_SUBJECT_PREFIX = '[AutoNew] '
