# Generated by Django 5.2.3 on 2025-07-01 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavado_auto', '0002_alter_usuario_options_remove_usuario_contrasena_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Solo para usuarios con rol "empresa". Los clientes no tienen empresa asignada.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='lavado_auto.empresa'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Administrador'), ('empresa', 'Empresa/Autolavado')], default='cliente', max_length=50),
        ),
    ]
