# Generated by Django 5.2.3 on 2025-07-01 12:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavado_auto', '0003_usuario_empresa_alter_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='empresa',
        ),
        migrations.AddField(
            model_name='empresa',
            name='contrasena',
            field=models.CharField(default='temp_password', max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Administrador')], default='cliente', max_length=50),
        ),
    ]
