# Generated by Django 5.2.3 on 2025-07-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavado_auto', '0004_remove_usuario_empresa_empresa_contrasena_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='verificada',
            field=models.BooleanField(default=False),
        ),
    ]
