# Generated by Django 5.1 on 2025-08-01 14:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavado_auto', '0005_empresa_verificada'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='es_pago_individual',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('basico', 'Lavado Básico'), ('premium', 'Limpieza Premium'), ('completo', 'Limpieza Completa')], max_length=20)),
                ('descripcion', models.TextField()),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_servicios_mes', models.IntegerField(help_text='Cantidad de servicios permitidos por mes. 0 = ilimitado')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('incluye_lavado_asientos', models.BooleanField(default=True)),
                ('incluye_aspirado', models.BooleanField(default=True)),
                ('incluye_lavado_exterior', models.BooleanField(default=True)),
                ('incluye_lavado_interior_humedo', models.BooleanField(default=False)),
                ('incluye_encerado', models.BooleanField(default=False)),
                ('incluye_detallado_completo', models.BooleanField(default=False)),
                ('servicios_incluidos', models.ManyToManyField(related_name='planes', to='lavado_auto.servicio')),
            ],
            options={
                'ordering': ['precio_mensual'],
            },
        ),
        migrations.CreateModel(
            name='SuscripcionUsuario',
            fields=[
                ('id_suscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('pausada', 'Pausada'), ('cancelada', 'Cancelada'), ('vencida', 'Vencida')], default='activa', max_length=20)),
                ('servicios_utilizados_mes', models.IntegerField(default=0)),
                ('ultimo_reinicio_contador', models.DateTimeField(default=django.utils.timezone.now)),
                ('auto_renovar', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lavado_auto.plan')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPagosSuscripcion',
            fields=[
                ('id_pago_suscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('referencia_pago', models.CharField(max_length=255, unique=True)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='lavado_auto.suscripcionusuario')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='suscripcion_utilizada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lavado_auto.suscripcionusuario'),
        ),
    ]
