# Generated by Django 5.1 on 2025-08-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavado_auto', '0006_reserva_es_pago_individual_plan_suscripcionusuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
    ]
