# Generated by Django 5.1 on 2025-08-04 18:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavado_auto', '0007_alter_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='conductor_asignado',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reserva',
            name='es_reserva_empresarial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='observaciones_empresariales',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='placa_vehiculo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedán'), ('suv', 'SUV'), ('camioneta', 'Camioneta'), ('bus', 'Bus'), ('microbus', 'Microbús'), ('camion', 'Camión'), ('taxi', 'Taxi'), ('moto', 'Motocicleta')], max_length=50),
        ),
        migrations.AddField(
            model_name='reservaservicio',
            name='descuento_empresarial',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento en porcentaje', max_digits=5),
        ),
        migrations.AddField(
            model_name='reservaservicio',
            name='precio_aplicado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio específico aplicado', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='DetalleReservaEmpresarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_interno_empresa', models.CharField(blank=True, help_text='Número interno de la empresa para el vehículo', max_length=50)),
                ('departamento_solicitante', models.CharField(blank=True, max_length=100)),
                ('centro_costo', models.CharField(blank=True, max_length=50)),
                ('kilometraje_actual', models.IntegerField(blank=True, null=True)),
                ('proxima_revision', models.DateField(blank=True, null=True)),
                ('responsable_vehiculo', models.CharField(blank=True, max_length=255)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_empresarial', to='lavado_auto.reserva')),
            ],
            options={
                'verbose_name': 'Detalle Reserva Empresarial',
                'verbose_name_plural': 'Detalles Reservas Empresariales',
            },
        ),
        migrations.CreateModel(
            name='PlanEmpresarial',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('basico_flota', 'Básico para Flotas'), ('premium_flota', 'Premium para Flotas'), ('corporativo', 'Plan Corporativo'), ('transporte_publico', 'Transporte Público')], max_length=30)),
                ('descripcion', models.TextField()),
                ('precio_mensual_por_vehiculo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_base_mensual', models.DecimalField(decimal_places=2, default=0, help_text='Precio base fijo mensual', max_digits=10)),
                ('vehiculos_minimos', models.IntegerField(default=5, help_text='Mínimo de vehículos para este plan')),
                ('vehiculos_maximos', models.IntegerField(blank=True, help_text='Máximo de vehículos (null = ilimitado)', null=True)),
                ('servicios_por_vehiculo_mes', models.IntegerField(help_text='Servicios permitidos por vehículo por mes. 0 = ilimitado')),
                ('descuento_volumen', models.DecimalField(decimal_places=2, default=0, help_text='Descuento por volumen en porcentaje', max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('incluye_lavado_asientos', models.BooleanField(default=True)),
                ('incluye_aspirado', models.BooleanField(default=True)),
                ('incluye_lavado_exterior', models.BooleanField(default=True)),
                ('incluye_lavado_interior_humedo', models.BooleanField(default=False)),
                ('incluye_encerado', models.BooleanField(default=False)),
                ('incluye_detallado_completo', models.BooleanField(default=False)),
                ('incluye_servicio_domicilio', models.BooleanField(default=False)),
                ('incluye_mantenimiento_programado', models.BooleanField(default=False)),
                ('incluye_reporte_mensual', models.BooleanField(default=False)),
                ('incluye_soporte_24_7', models.BooleanField(default=False)),
                ('servicios_incluidos', models.ManyToManyField(related_name='planes_empresariales', to='lavado_auto.servicio')),
            ],
            options={
                'verbose_name': 'Plan Empresarial',
                'verbose_name_plural': 'Planes Empresariales',
                'ordering': ['precio_mensual_por_vehiculo'],
            },
        ),
        migrations.CreateModel(
            name='SuscripcionEmpresarial',
            fields=[
                ('id_suscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_vehiculos', models.IntegerField()),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('pausada', 'Pausada'), ('cancelada', 'Cancelada'), ('vencida', 'Vencida')], default='activa', max_length=20)),
                ('servicios_utilizados_mes', models.IntegerField(default=0)),
                ('ultimo_reinicio_contador', models.DateTimeField(default=django.utils.timezone.now)),
                ('auto_renovar', models.BooleanField(default=True)),
                ('precio_mensual_actual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contacto_responsable', models.CharField(max_length=255)),
                ('telefono_contacto', models.CharField(max_length=15)),
                ('notas_especiales', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones_empresariales', to='lavado_auto.empresa')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lavado_auto.planempresarial')),
            ],
            options={
                'verbose_name': 'Suscripción Empresarial',
                'verbose_name_plural': 'Suscripciones Empresariales',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPagosSuscripcionEmpresarial',
            fields=[
                ('id_pago_suscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('referencia_pago', models.CharField(max_length=255, unique=True)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('periodo_facturado', models.CharField(help_text='Ej: 2024-01', max_length=20)),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='lavado_auto.suscripcionempresarial')),
            ],
            options={
                'verbose_name': 'Pago Suscripción Empresarial',
                'verbose_name_plural': 'Pagos Suscripciones Empresariales',
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='suscripcion_empresarial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lavado_auto.suscripcionempresarial'),
        ),
    ]
