# Generated by Django 5.1 on 2025-08-06 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavado_auto', '0008_reserva_conductor_asignado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudServicioEmpresa',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('en_revision', 'En Revisión')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('motivo_solicitud', models.TextField(help_text='Razón por la cual necesita este servicio')),
                ('respuesta_admin', models.TextField(blank=True, help_text='Respuesta del administrador')),
                ('usuario_responsable', models.CharField(help_text='Persona responsable de la solicitud', max_length=255)),
                ('telefono_contacto', models.CharField(help_text='Teléfono para contacto', max_length=15)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_servicios', to='lavado_auto.empresa')),
                ('servicio_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lavado_auto.servicio')),
            ],
            options={
                'verbose_name': 'Solicitud de Servicio Empresa',
                'verbose_name_plural': 'Solicitudes de Servicios Empresas',
                'unique_together': {('empresa', 'servicio_solicitado', 'estado')},
            },
        ),
    ]
