# Generated by Django 5.1 on 2025-09-04 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavado_auto', '0011_usuario_failed_login_attempts_usuario_is_locked_out_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensajequeja',
            options={'ordering': ['-fecha_envio'], 'verbose_name': 'PQRS', 'verbose_name_plural': 'PQRS'},
        ),
        migrations.AddField(
            model_name='mensajequeja',
            name='acepto_terminos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensajequeja',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mensajequeja',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mensajequeja',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensajequeja',
            name='nombre_contacto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mensajequeja',
            name='numero_radicado',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mensajequeja',
            name='servicio_bd',
            field=models.ForeignKey(blank=True, help_text='Servicio seleccionado de la base de datos', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lavado_auto.servicio'),
        ),
        migrations.AddField(
            model_name='mensajequeja',
            name='servicio_relacionado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mensajequeja',
            name='tipo_pqrs',
            field=models.CharField(choices=[('peticion', 'Petición'), ('queja', 'Queja'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia')], default='peticion', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensajequeja',
            name='urgencia',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20),
        ),
        migrations.AlterField(
            model_name='mensajequeja',
            name='estado',
            field=models.CharField(choices=[('recibido', 'Recibido'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='recibido', max_length=20),
        ),
        migrations.AlterField(
            model_name='mensajequeja',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mensajequeja',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
