# Generated by Django 5.1 on 2025-09-24 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavado_auto', '0013_empresa_latitud_empresa_longitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudContactoPlan',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('empresa', models.CharField(max_length=200)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('cantidad_vehiculos', models.IntegerField(help_text='Cantidad aproximada de vehículos en la flota')),
                ('mensaje_adicional', models.TextField(blank=True, help_text='Información adicional o requerimientos específicos')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('contactado', 'Contactado'), ('cerrado', 'Cerrado')], default='pendiente', max_length=20)),
                ('ip_solicitante', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('fecha_contacto', models.DateTimeField(blank=True, null=True)),
                ('notas_seguimiento', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_contacto', to='lavado_auto.planempresarial')),
            ],
            options={
                'verbose_name': 'Solicitud de Contacto de Plan',
                'verbose_name_plural': 'Solicitudes de Contacto de Planes',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
