# Generated by Django 5.1 on 2025-10-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavado_auto', '0014_solicitudcontactoplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='token_reset',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
