# Generated by Django 5.1 on 2025-10-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavado_auto', '0015_empresa_token_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcontactoplan',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('contactado', 'Contactado'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cerrado', 'Cerrado')], default='pendiente', max_length=20),
        ),
    ]
