# Generated by Django 5.1 on 2025-10-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavado_auto', '0016_alter_solicitudcontactoplan_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='first_warning_sent',
            field=models.BooleanField(default=False),
        ),
    ]
