# Generated by Django 5.1 on 2025-10-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lavado_auto', '0017_usuario_first_warning_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_locked_out',
        ),
    ]
