# Generated by Django 5.1 on 2025-10-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavado_auto', '0018_remove_usuario_is_locked_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='first_warning_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='last_failed_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='lockout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
