# Generated by Django 5.1 on 2025-10-09 19:16

from django.db import migrations, models
import django.db.models.deletion


def migrar_servicios_existentes(apps, schema_editor):
    """
    Migra los servicios existentes de la relación ManyToMany
    al nuevo modelo PlanServicio con descuento en 0%
    """
    Plan = apps.get_model('lavado_auto', 'Plan')
    PlanServicio = apps.get_model('lavado_auto', 'PlanServicio')
    
    for plan in Plan.objects.all():
        for servicio in plan.servicios_incluidos.all():
            PlanServicio.objects.create(
                plan=plan,
                servicio=servicio,
                porcentaje_descuento=0.00
            )


class Migration(migrations.Migration):

    dependencies = [
        ('lavado_auto', '0019_empresa_failed_login_attempts_and_more'),
    ]

    operations = [
        # Paso 1: Crear el modelo PlanServicio
        migrations.CreateModel(
            name='PlanServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de descuento aplicado a este servicio (0-100)', max_digits=5)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_servicios', to='lavado_auto.plan')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicio_planes', to='lavado_auto.servicio')),
            ],
            options={
                'verbose_name': 'Plan-Servicio',
                'verbose_name_plural': 'Planes-Servicios',
                'unique_together': {('plan', 'servicio')},
            },
        ),
        
        # Paso 2: Migrar datos existentes
        migrations.RunPython(migrar_servicios_existentes, reverse_code=migrations.RunPython.noop),
        
        # Paso 3: Eliminar el campo ManyToMany antiguo
        migrations.RemoveField(
            model_name='plan',
            name='servicios_incluidos',
        ),
        
        # Paso 4: Crear el nuevo campo ManyToMany con through
        migrations.AddField(
            model_name='plan',
            name='servicios_incluidos',
            field=models.ManyToManyField(related_name='planes', through='lavado_auto.PlanServicio', to='lavado_auto.servicio'),
        ),
    ]
