# Generated by Django 5.1 on 2025-10-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavado_auto', '0020_crear_plan_servicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservaservicio',
            options={'verbose_name': 'Servicio de Reserva', 'verbose_name_plural': 'Servicios de Reservas'},
        ),
        migrations.AddField(
            model_name='reservaservicio',
            name='descuento_plan_individual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento del plan individual en porcentaje (desde PlanServicio)', max_digits=5),
        ),
        migrations.AddField(
            model_name='reservaservicio',
            name='es_servicio_plan',
            field=models.BooleanField(default=False, help_text='Indica si este servicio es parte del plan individual del usuario'),
        ),
        migrations.AddField(
            model_name='reservaservicio',
            name='precio_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio original del servicio (sin descuentos)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reservaservicio',
            name='descuento_empresarial',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento empresarial en porcentaje', max_digits=5),
        ),
        migrations.AlterField(
            model_name='reservaservicio',
            name='precio_aplicado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio final aplicado con descuentos', max_digits=10, null=True),
        ),
    ]
