# Generated by Django 5.1 on 2025-10-10 20:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavado_auto', '0021_alter_reservaservicio_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_por_periodo', models.IntegerField(default=15, help_text='Días por período de liquidación')),
                ('comision_por_defecto', models.DecimalField(decimal_places=2, default=15.0, help_text='Comisión por defecto (%)', max_digits=5)),
                ('dias_aviso_vencimiento', models.IntegerField(default=3, help_text='Días de anticipación para avisar vencimiento')),
                ('auto_cerrar_periodos', models.BooleanField(default=False, help_text='Cerrar automáticamente períodos vencidos')),
                ('incluir_reservas_canceladas', models.BooleanField(default=False, help_text='Incluir reservas canceladas en reportes')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Pagos',
                'verbose_name_plural': 'Configuraciones de Pagos',
            },
        ),
        migrations.CreateModel(
            name='PeriodoLiquidacion',
            fields=[
                ('id_periodo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('total_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comision_autonew', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('total_comision', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_neto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('cerrado', 'Cerrado'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='activo', max_length=20)),
                ('cantidad_reservas', models.IntegerField(default=0)),
                ('metodo_pago', models.CharField(blank=True, choices=[('transferencia', 'Transferencia Bancaria'), ('consignacion', 'Consignación'), ('efectivo', 'Efectivo'), ('cheque', 'Cheque')], max_length=50)),
                ('referencia_pago', models.CharField(blank=True, max_length=255)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_liquidacion', to='lavado_auto.empresa')),
                ('pagado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_pagados', to=settings.AUTH_USER_MODEL)),
                ('reservas_incluidas', models.ManyToManyField(blank=True, related_name='periodos_liquidacion', to='lavado_auto.reserva')),
            ],
            options={
                'verbose_name': 'Período de Liquidación',
                'verbose_name_plural': 'Períodos de Liquidación',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DetalleLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_neto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comision_aplicada', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_comision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_final_empresa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_servicio', models.DateTimeField()),
                ('tipo_descuento', models.CharField(blank=True, choices=[('plan_individual', 'Plan Individual'), ('plan_empresarial', 'Plan Empresarial'), ('descuento_especial', 'Descuento Especial'), ('sin_descuento', 'Sin Descuento')], max_length=50)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lavado_auto.reserva')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='lavado_auto.periodoliquidacion')),
            ],
            options={
                'verbose_name': 'Detalle de Liquidación',
                'verbose_name_plural': 'Detalles de Liquidación',
                'unique_together': {('periodo', 'reserva')},
            },
        ),
    ]
