# Generated by Django 5.1 on 2025-10-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavado_auto', '0022_configuracionpagos_periodoliquidacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='numero_reserva',
            field=models.CharField(blank=True, help_text='Número único de reserva generado automáticamente', max_length=15, null=True),
        ),
    ]
