# Generated by Django 5.1 on 2025-10-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavado_auto', '0023_add_numero_reserva_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='numero_reserva',
            field=models.CharField(blank=True, help_text='Número único de reserva generado automáticamente', max_length=15, null=True, unique=True),
        ),
    ]
