# Generated by Django 5.1 on 2025-10-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavado_auto', '0024_make_numero_reserva_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='pagado_empresa',
            field=models.BooleanField(default=False, help_text='Indica si el pago correspondiente a la reserva fue transferido/pagado a la empresa', verbose_name='Pagado a la empresa'),
        ),
    ]
