# Generated by Django 5.1 on 2025-11-03 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavado_auto', '0025_reserva_pagado_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='banco',
            field=models.CharField(blank=True, help_text='Nombre del banco donde está la cuenta', max_length=100, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='datos_bancarios_verificados',
            field=models.BooleanField(default=False, help_text='Indica si los datos bancarios han sido verificados por el administrador', verbose_name='Datos bancarios verificados'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_facturacion',
            field=models.EmailField(blank=True, help_text='Email para enviar facturas y notificaciones de pagos', max_length=254, null=True, verbose_name='Email de facturación'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_verificacion_bancaria',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se verificaron los datos bancarios', null=True, verbose_name='Fecha de verificación bancaria'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='iban',
            field=models.CharField(blank=True, help_text='Número IBAN (para pagos internacionales)', max_length=50, null=True, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nit_empresa',
            field=models.CharField(blank=True, help_text='NIT de la empresa', max_length=20, null=True, verbose_name='NIT'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='notas_bancarias',
            field=models.TextField(blank=True, help_text='Notas adicionales sobre la información bancaria o instrucciones especiales para pagos', null=True, verbose_name='Notas bancarias'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero_cuenta',
            field=models.CharField(blank=True, help_text='Número de cuenta bancaria para recibir pagos', max_length=50, null=True, verbose_name='Número de cuenta'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero_documento_titular',
            field=models.CharField(blank=True, help_text='Número de documento del titular de la cuenta', max_length=50, null=True, verbose_name='Número de documento'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Razón social de la empresa (si es diferente al nombre comercial)', max_length=255, null=True, verbose_name='Razón social'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='regimen_tributario',
            field=models.CharField(blank=True, choices=[('simplificado', 'Régimen Simplificado'), ('comun', 'Régimen Común'), ('especial', 'Régimen Especial')], help_text='Régimen tributario de la empresa', max_length=50, null=True, verbose_name='Régimen tributario'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='responsable_pagos',
            field=models.CharField(blank=True, help_text='Nombre de la persona responsable de gestionar los pagos', max_length=255, null=True, verbose_name='Responsable de pagos'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='swift_code',
            field=models.CharField(blank=True, help_text='Código SWIFT del banco (para transferencias internacionales)', max_length=20, null=True, verbose_name='Código SWIFT'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefono_facturacion',
            field=models.CharField(blank=True, help_text='Teléfono de contacto para temas de facturación', max_length=15, null=True, verbose_name='Teléfono de facturación'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_cuenta',
            field=models.CharField(blank=True, choices=[('ahorros', 'Cuenta de Ahorros'), ('corriente', 'Cuenta Corriente')], help_text='Tipo de cuenta bancaria', max_length=20, null=True, verbose_name='Tipo de cuenta'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_documento_titular',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('NIT', 'NIT'), ('CE', 'Cédula de Extranjería'), ('PAS', 'Pasaporte')], help_text='Tipo de documento del titular', max_length=20, null=True, verbose_name='Tipo de documento'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='titular_cuenta',
            field=models.CharField(blank=True, help_text='Nombre completo del titular de la cuenta bancaria', max_length=255, null=True, verbose_name='Titular de la cuenta'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='verificado_por',
            field=models.ForeignKey(blank=True, help_text='Administrador que verificó los datos bancarios', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_verificadas', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por'),
        ),
    ]
