# Generated by Django 5.1 on 2025-11-09 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lavado_auto', '0026_add_empresa_banking_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='profile_picture',
        ),
    ]
