# Generated by Django 5.2.3 on 2025-11-11 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavado_auto', '0027_remove_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentimientoUsuario',
            fields=[
                ('id_consentimiento', models.AutoField(primary_key=True, serialize=False)),
                ('acepta_politica_privacidad', models.BooleanField(default=False, verbose_name='Acepta Aviso de Privacidad')),
                ('acepta_tratamiento_datos', models.BooleanField(default=False, verbose_name='Acepta Política de Tratamiento de Datos')),
                ('acepta_terminos_condiciones', models.BooleanField(default=False, verbose_name='Acepta Términos y Condiciones')),
                ('acepta_comunicaciones_comerciales', models.BooleanField(default=False, verbose_name='Acepta Comunicaciones Comerciales')),
                ('acepta_compartir_datos_terceros', models.BooleanField(default=False, verbose_name='Acepta Compartir Datos con Terceros')),
                ('tipo_consentimiento', models.CharField(choices=[('registro', 'Registro Inicial'), ('actualizacion', 'Actualización de Políticas'), ('marketing', 'Comunicaciones de Marketing')], default='registro', max_length=20)),
                ('fecha_consentimiento', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='Navegador/Dispositivo')),
                ('version_politica_privacidad', models.CharField(default='1.0', max_length=20)),
                ('version_tratamiento_datos', models.CharField(default='1.0', max_length=20)),
                ('version_terminos_condiciones', models.CharField(default='1.0', max_length=20)),
                ('revocado', models.BooleanField(default=False, verbose_name='Consentimiento Revocado')),
                ('fecha_revocacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_revocacion', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consentimiento de Usuario',
                'verbose_name_plural': 'Consentimientos de Usuarios',
                'ordering': ['-fecha_consentimiento'],
                'indexes': [models.Index(fields=['usuario', 'fecha_consentimiento'], name='lavado_auto_usuario_a9b547_idx'), models.Index(fields=['revocado'], name='lavado_auto_revocad_e0a685_idx')],
            },
        ),
    ]
